"""
topic_sourcer.py — Shared 3-tier topic sourcing for all blog scripts.

Called by 6-india-blog.py, 7-spanish-blog.py, 9-arabic-blog.py to get
properly sourced topics instead of hardcoded lists.

Tier 1: GHL docs — adapt English blog posts sourced from help.gohighlevel.com
Tier 2: GSC gaps — queries with impressions but no matching page in target language
Tier 3: Market-specific — industry verticals generated by Claude

Usage:
    from topic_sourcer import get_topics
    topics = get_topics(language="es", limit=5, published=published_records)
"""

import json
import re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
SITE_POSTS_DIR = Path("/opt/globalhighlevel-site/posts") if Path("/opt/globalhighlevel-site/posts").exists() else BASE_DIR.parent / "globalhighlevel-site" / "posts"
GSC_DATA_FILE = DATA_DIR / "gsc-stats.json"
PUBLISHED_FILE = DATA_DIR / "published.json"
TOPIC_WEIGHTS_FILE = DATA_DIR / "topic-weights.json"


def _load_json(path):
    if path.exists():
        return json.loads(path.read_text())
    return []


def _get_english_posts_with_source():
    """Get English blog posts that were sourced from GHL help docs (have articleId)."""
    posts = []
    if not SITE_POSTS_DIR.exists():
        return posts
    for f in SITE_POSTS_DIR.glob("*.json"):
        try:
            data = json.loads(f.read_text())
            if data.get("articleId") and data.get("language", "en") == "en":
                posts.append({
                    "articleId": data["articleId"],
                    "title": data.get("title", ""),
                    "slug": data.get("slug", ""),
                    "description": data.get("description", ""),
                    "html_content": data.get("html_content", "")[:3000],  # first 3K chars as context
                    "category": data.get("category", ""),
                })
        except Exception:
            continue
    return posts


def _get_topic_weights():
    """Load topic weights for prioritization."""
    if TOPIC_WEIGHTS_FILE.exists():
        try:
            data = json.loads(TOPIC_WEIGHTS_FILE.read_text())
            hot = set(data.get("hot_keywords", []))
            return hot
        except Exception:
            pass
    return set()


def get_tier1_topics(language: str, published: list, limit: int = 3) -> list:
    """
    Tier 1: GHL docs — find English posts sourced from help.gohighlevel.com
    that haven't been adapted for this language yet.

    Returns list of dicts with source material for the writer.
    """
    english_posts = _get_english_posts_with_source()
    if not english_posts:
        return []

    # Which articleIds are already covered in this language?
    done_ids = set()
    for r in published:
        aid = r.get("articleId")
        if aid:
            done_ids.add(str(aid))

    # Filter to uncovered articles
    uncovered = [p for p in english_posts if str(p["articleId"]) not in done_ids]

    # Prioritize by topic weight (hot keywords in title)
    hot_keywords = _get_topic_weights()
    if hot_keywords:
        def score(p):
            title_lower = p["title"].lower()
            return sum(1 for kw in hot_keywords if kw.lower() in title_lower)
        uncovered.sort(key=score, reverse=True)

    topics = []
    for p in uncovered[:limit]:
        topics.append({
            "topic": p["title"],
            "source": "tier1-docs",
            "tier": 1,
            "articleId": p["articleId"],
            "english_title": p["title"],
            "english_description": p["description"],
            "english_content_preview": p["html_content"],
            "category": p["category"],
        })

    return topics


def get_tier2_topics(language: str, published: list, limit: int = 1) -> list:
    """
    Tier 2: GSC gaps — queries from target-language countries with no matching page.
    """
    lang_key_map = {"es": "queries_es", "en-IN": "queries_in", "ar": "queries_ar"}
    key = lang_key_map.get(language)
    if not key:
        return []

    if not GSC_DATA_FILE.exists():
        return []

    try:
        gsc = json.loads(GSC_DATA_FILE.read_text())
    except Exception:
        return []

    lang_queries = gsc.get(key, [])
    if not lang_queries:
        return []

    # Check which queries already have a matching page
    existing_slugs = set()
    existing_titles = set()
    if SITE_POSTS_DIR.exists():
        for f in SITE_POSTS_DIR.glob("*.json"):
            try:
                data = json.loads(f.read_text())
                if data.get("language") == language:
                    existing_slugs.add(data.get("slug", "").lower())
                    existing_titles.add(data.get("title", "").lower())
            except Exception:
                continue

    # Also check published records
    for r in published:
        slug = r.get("slug", r.get("blogSlug", ""))
        if slug:
            existing_slugs.add(slug.lower())

    topics = []
    for q in lang_queries:
        query = q["query"].lower()
        # Skip if we likely have a page for this
        if any(query in slug or slug in query for slug in existing_slugs):
            continue
        if any(query in title for title in existing_titles):
            continue
        if q.get("impressions", 0) < 10:
            continue

        topics.append({
            "topic": q["query"],
            "source": "tier2-gsc",
            "tier": 2,
            "impressions": q.get("impressions", 0),
            "position": q.get("position", 0),
            "country": q.get("country", ""),
        })

        if len(topics) >= limit:
            break

    return topics


def get_tier3_topics(language: str, published: list, limit: int = 1) -> list:
    """
    Tier 3: Market-specific — return placeholder topics for the existing
    auto-generation logic in each blog script to handle.

    Returns empty list — the blog scripts' existing Claude topic generation
    serves as Tier 3. This function is a hook for future enhancement.
    """
    # The existing blog scripts already auto-generate topics via Claude
    # when they run low. That IS Tier 3. No need to duplicate here.
    return []


def get_topics(language: str, published: list, limit: int = 5) -> list:
    """
    Get prioritized topics from all 3 tiers.

    Default distribution: 3 Tier 1 + 1 Tier 2 + 1 Tier 3
    Falls back to more Tier 1 if other tiers are empty.
    """
    tier1 = get_tier1_topics(language, published, limit=3)
    tier2 = get_tier2_topics(language, published, limit=1)
    tier3 = get_tier3_topics(language, published, limit=1)

    topics = tier1 + tier2 + tier3

    # Fill remaining slots from Tier 1 if other tiers are short
    remaining = limit - len(topics)
    if remaining > 0:
        extra_tier1 = get_tier1_topics(language, published, limit=remaining + 3)
        # Skip ones we already have
        existing_ids = {t.get("articleId") for t in topics if t.get("articleId")}
        for t in extra_tier1:
            if t.get("articleId") not in existing_ids and len(topics) < limit:
                topics.append(t)

    return topics[:limit]
